# Model arguments
model_name_or_path: Qwen/Qwen3-Coder-30B-A3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2


use_peft: true
load_in_8bit: true
lora_r: 16           # 스모크용: 작게 시작 → 안정되면 32로
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_up_proj
  - down_proj

# Data training arguments
dataset_name: chansung/verifiable-coding-problems-python-v2
dataset_prompt_column: problem
system_prompt: "You are a helpful AI Assistant specialized in Python programming that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# GRPO trainer config
beta: 0.01
bf16: true
use_vllm: true
do_eval: false
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen3-Coder-30B-A3B-CCRL-CUR-UNI-1E
hub_strategy: every_save
learning_rate: 1e-6 # 5.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant # cosine_with_min_lr
# lr_scheduler_kwargs:
#   min_lr_rate: 0.1
max_prompt_length: 1024
max_completion_length: 4096
# max_steps: 1000
num_generations: 7
num_train_epochs: 1
output_dir: data/Qwen3-Coder-30B-A3B-CCRL-CUR-UNI-1E
overwrite_output_dir: true
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- wandb
reward_funcs:
- code_format
- curriculum_aware_reward_fn
reward_weights:
- 1.0
- 1.0
save_strategy: "epoch"
# save_steps: 1000
save_total_limit: 2
seed: 42
temperature: 1.0
# warmup_ratio: 0.03
warmup_ratio: 0.0
